#version 460


layout(rgba32f, binding=0) uniform image2D layered;
layout(rgba32f, binding=1) uniform image2D summed;
uniform int nlayers;

layout(local_size_x=16, local_size_y=16) in;
void main(){

    ivec2 size = imageSize(summed);
    ivec2 pixCoord = ivec2(gl_GlobalInvocationID.xy);

    vec4 sum = vec4(0.);
    for (int i = 0; i<=nlayers; i++){
        sum += imageLoad(layered, pixCoord+i*ivec2(size.x, 0));
    }
    
    imageStore(summed, pixCoord, sum);

}